---

- name: Setup DebOps via Vagrant
  hosts: all
  become: True

  roles:
    - role: ganto.vagrant_debops


- name: Setup Check_MK server role
  hosts: debops_service_checkmk_server
  gather_facts: False

  tasks:

    - name: Get debops-contrib.checkmk_server from Ansible Galaxy
      command: ansible-galaxy install --roles-path /home/vagrant/vagrant-debops/ansible/roles --no-deps debops-contrib.checkmk_server

    - name: Link checkmk_server playbook
      file:
        src: /home/vagrant/vagrant-debops/ansible/roles/debops-contrib.checkmk_server/docs/playbooks/checkmk_server.yml
        path: /home/vagrant/vagrant-debops/ansible/playbooks/checkmk_server.yml
        state: link


- name: Setup Check_MK agent role
  hosts: debops_service_checkmk_agent
  gather_facts: False

  tasks:

    - name: Get debops-contrib.checkmk_agent from Ansible Galaxy
      command: ansible-galaxy install --roles-path /home/vagrant/vagrant-debops/ansible/roles --no-deps debops-contrib.checkmk_agent

    - name: Link checkmk_agent playbook
      file:
        src: /home/vagrant/vagrant-debops/ansible/roles/debops-contrib.checkmk_agent/docs/playbooks/checkmk_agent.yml
        path: /home/vagrant/vagrant-debops/ansible/playbooks/checkmk_agent.yml
        state: link
