# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider :libvirt do |v,override|
        override.vm.box = "centos/7"
        override.vm.synced_folder '.', '/home/vagrant/sync', disabled: true
    end
    config.vm.provider :virtualbox do |v|
        config.vm.box = "bento/centos-7.1"
    end

    config.vm.define :heketi do |heketi|
        heketi.vm.network :private_network, ip: "192.168.10.100"
        heketi.vm.host_name = "heketi.example.com"
        heketi.vm.provider :virtualbox do |vb|
            vb.memory = 512
            vb.cpus = 2
            vb.customize [ "createhd", "--filename", "disk-gluster.vdi", "--size", 500*1024 ]
            vb.customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 4, "--device", 0, "--type", "hdd", "--medium", "disk-gluster.vdi" ]
        end

        heketi.vm.provider :libvirt do |lv|
            lv.memory = 512
            lv.cpus = 2
            lv.storage :file, :device => "vdb", :path => "disk-gluster.qcow2", :size => '500G'
        end

        # View the documentation for the provider you're using for more
        # information on available options.
        heketi.vm.provision :ansible do |ansible|
            ansible.limit = "all"
            ansible.playbook = "site.yml"
            ansible.groups = {
                "client" => ["heketi"],
                "heketi" => ["heketi"],
                "gluster" => ["heketi"],
            }
        end
    end
end
