---

- name: Setup DebOps via Vagrant
  hosts: all
  become: True

  roles:
    - role: ganto.vagrant_debops


- name: Setup Roundcube role
  hosts: debops_service_roundcube
  gather_facts: False

  tasks:

    - name: Get debops-contrib.roundcube from Ansible Galaxy
      command: ansible-galaxy install --roles-path /home/vagrant/vagrant-debops/ansible/roles --no-deps --force debops-contrib.roundcube

    - name: Link roundcube playbook
      file:
        src: /home/vagrant/vagrant-debops/ansible/roles/debops-contrib.roundcube/docs/playbooks/roundcube.yml
        path: /home/vagrant/vagrant-debops/ansible/playbooks/roundcube.yml
        state: link
